# Generated by Django 3.2.16 on 2022-12-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_kh6p7i', upload_to='images/'),
        ),
    ]
