# Generated by Django 3.2.16 on 2023-01-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221219_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='', max_length=300),
        ),
    ]
