# Generated by Django 3.2.16 on 2023-01-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230121_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cost',
        ),
    ]
